### ISSUE TITLE
Integrate Alex.js linter

### ISSUE THREAD

**Issue by carolstran** [unmock/unmock.github.io#38]
We want to make sure that our documentation doesn't use an insensitive or offensive language. So it'd be great to integrate the [Alex.js](https://alexjs.com/) linter into our build process and CI tests. Alex is powered by [retext-equality](https://github.com/retextjs/retext-equality/blob/master/rules.md) so combats against language that is condescending, ableist, homophobic, gendered, racist, references self-harm and more. 

The React Native team recently implemented this. You can [follow these steps](https://twitter.com/rickhanlonii/status/1183790093770940416?s=20) and/or use their [PR for reference](https://github.com/facebook/react-native-website/commit/0c9962b4ea70df86796c00c17782d3c5a92bc20a).

**Comment by theashraf** [comment]
i'd like to work on this issue

**Comment by carolstran** [comment]
That'd be amazing, thank you @theashraf 🎉
