### ISSUE TITLE
Fix linted issues in docs/

### ISSUE THREAD

**Issue by carolstran** [unmock/unmock.github.io#42]
Now that we've integrated the Alex linter from #38 - we need to fix all of the issues that it found in the documentation! Until this is done, I've designated in the `.alexignore` file to ignore our docs directory. 

@theashraf - GitHub won't let me assign this issue to you straight away but after our conversation in #41, I'm going to assume you're on this one and label it `in progress` 🙌

**Comment by theashraf** [comment]
Great, thank you
I'll work on it :+1:
